pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sewalewsetotaw/alx-backend-python.git',
                    credentialsId: 'sewalewsetotaw'
            }
        }

        stage('Setup Python Environment') {
            steps {
                // Create virtual environment
                sh 'python3 -m venv $VENV_DIR'
                // Upgrade pip and install dependencies
                sh '. $VENV_DIR/bin/activate && pip install --upgrade pip'
                sh '. $VENV_DIR/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                // Run pytest and generate report
                sh '. $VENV_DIR/bin/activate && pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
                archiveArtifacts artifacts: 'report.xml', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
    }
}
