
services:
  db:
    image: mysql:8.0
    env_file:
     - .env
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 --timeout=30 --strict -- \
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
             
    volumes:
      - .:/app
    env_file:
     - .env
    ports:
      - "8001:8000"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - db

volumes:
  mysql-data: