#!/bin/bash
set -e

echo "Deploying Blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying Green version..."
kubectl apply -f green_deployment.yaml

echo "Applying service routing..."
kubectl apply -f kubeservice.yaml

echo "Checking logs for Green version..."
kubectl logs -l version=green --tail=20

echo "Blue-Green deployment setup complete ✅"
